import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import type {Deployment} from '../types';
import {pinhaotuanAbi} from '../generated/abi';
import {reader} from '../lib/chain';
import {Amount,destination} from './shared';
import { i18nText } from "../lib/i18n";
export interface CatalogEntry {id:string;category:string;key?:string;label?:string;featured?:boolean}
interface Card {id:string;title:string;summary:string;hostName:string;cost:bigint;quote:bigint|null;count:number;minimum:number;capacity:number;funded:boolean;status:number;deadline:bigint;blockNumber:bigint;timestamp:bigint;fetchedAt:number;error?:string}
const names:Record<string,string>={all:i18nText('全部活动'),ai:i18nText('AI 拼车'),learning:i18nText('小班共创'),space:i18nText('场地分摊'),community:i18nText('社群活动'),history:i18nText('退款与结算')};
export function cardStatus(g:Card){if(g.status===1)return i18nText('已取消 · 可退款');if(g.status===2||(!g.funded&&g.timestamp>=g.deadline))return i18nText('未成团 · 可退款');if(g.status===3)return i18nText('已结算');if(g.timestamp>=g.deadline)return i18nText('已截止 · 待结算');if(g.count>=g.capacity)return i18nText('已满员 · 等待截止');if(g.funded)return i18nText('已成团 · 继续报名');return i18nText("预报名 · 还差 {0} 人", g.minimum-g.count);}
export function useGroupCards(d:Deployment,ids:string[]){
 const identity=ids.join(',');const [cards,setCards]=useState<Record<string,Card>>({});const [loading,setLoading]=useState(false);const [error,setError]=useState('');const alive=useRef(0);const pending=useRef<string|null>(null);
 const reload=useCallback(async()=>{const generation=alive.current;const job=`${generation}:${identity}`;if(pending.current===job)return;pending.current=job;setLoading(true);setError('');try{
  const c=reader(d),block=await c.getBlock();const newCards:Record<string,Card>={};
  for(let offset=0;offset<ids.length;offset+=3){await Promise.all(ids.slice(offset,offset+3).map(async id=>{try{
   const g=await c.readContract({address:d.contract,abi:pinhaotuanAbi,functionName:'getGroup',args:[BigInt(id)],blockNumber:block.number});let meta:Record<string,unknown>={};try{meta=JSON.parse(g.metadataJson)}catch{}
   const text=(key:string,fallback:string)=>typeof meta[key]==='string'?meta[key] as string:fallback;
   const open=g.status===0&&block.timestamp<g.deadline&&g.activeMembers.length<g.capacity;
   let quote:bigint|null=null;if(open){const q=await c.readContract({address:d.contract,abi:pinhaotuanAbi,functionName:'quoteJoin',args:[BigInt(id)],blockNumber:block.number});quote=q[0]}
   newCards[id]={id,title:text('title',i18nText("活动 #{0}", id)),summary:text('summary',i18nText('链上活动')),hostName:text('hostName',i18nText('主办方')),cost:g.cost,quote,count:g.activeMembers.length,minimum:g.minimum,capacity:g.capacity,funded:g.funded,status:g.status,deadline:g.deadline,blockNumber:block.number,timestamp:block.timestamp,fetchedAt:Date.now()};
  }catch(e){newCards[id]={id,title:i18nText("活动 #{0}", id),summary:i18nText('读取暂未完成'),hostName:'',cost:0n,quote:null,count:0,minimum:0,capacity:0,funded:false,status:0,deadline:0n,blockNumber:block.number,timestamp:block.timestamp,fetchedAt:Date.now(),error:e instanceof Error?e.message.slice(0,120):i18nText('RPC读取失败')};}}));}
  if(generation===alive.current)setCards(previous=>{const next={...previous};for(const [id,card]of Object.entries(newCards)){if(!next[id]||card.blockNumber>=next[id].blockNumber)next[id]=card}return next});
 }catch(e){if(generation===alive.current)setError(e instanceof Error?e.message.slice(0,180):i18nText('无法读取活动列表'));}finally{if(pending.current===job)pending.current=null;if(generation===alive.current)setLoading(false)}},[d.chainId,d.contract,d.rpcUrl,identity]);
 useEffect(()=>{alive.current++;setCards({});void reload();const id=setInterval(()=>{if(document.visibilityState==='visible')void reload()},12000);return()=>{alive.current++;clearInterval(id)}},[reload]);
 return {cards,loading,error,reload};
}
export function GroupCatalog({deployment:d}:{deployment:Deployment}){
 const [entries,setEntries]=useState<CatalogEntry[]>([]),[catalogError,setCatalogError]=useState(''),[category,setCategory]=useState('all'),[query,setQuery]=useState(''),[nonce,setNonce]=useState(0);
 useEffect(()=>{let active=true;setCatalogError('');fetch('/catalog.json',{cache:'no-store'}).then(async response=>{if(!response.ok)throw Error(i18nText('活动目录暂未配置'));const v=await response.json();if(v.chainId!==d.chainId||String(v.contract).toLowerCase()!==d.contract.toLowerCase()||String(v.token).toLowerCase()!==d.token.toLowerCase()||!Array.isArray(v.groups))throw Error(i18nText('活动目录与当前部署不匹配，已停止展示'));const seen=new Set<string>();const valid=v.groups.filter((e:CatalogEntry)=>/^\d+$/.test(String(e.id))&&typeof e.category==='string'&&!seen.has(String(e.id))&&(seen.add(String(e.id)),true));if(active)setEntries(valid.map((e:CatalogEntry)=>({...e,id:String(e.id)})));}).catch(e=>{if(active)setCatalogError(e.message)});return()=>{active=false}},[d.chainId,d.contract,d.token,nonce]);
 const ids=useMemo(()=>entries.map(e=>e.id),[entries]);const {cards,loading,error,reload}=useGroupCards(d,ids);
 const [now,setNow]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
 const rank=(e:CatalogEntry)=>{const g=cards[e.id];const active=g&&!g.error&&g.status===0&&g.timestamp<g.deadline;return e.featured?0:active?1:2};
 const shown=entries.filter(e=>{const g=cards[e.id];const history=g&&(g.status!==0||g.timestamp>=g.deadline);return(category==='all'||category==='history'&&history||category===e.category)&&(!query||`${g?.title||''} ${e.id} ${g?.summary||''}`.toLowerCase().includes(query.toLowerCase()))}).sort((a,b)=>rank(a)-rank(b));
 return <section className="catalog" aria-labelledby="catalog-title"><div className="section-head"><div><p className="stat-label">{i18nText("多场景 · 同一套分摊规则")}</p><h2 id="catalog-title">{i18nText("挑一个团，看懂钱如何分。")}</h2></div><button className="secondary" onClick={()=>{setNonce(x=>x+1);void reload()}} disabled={loading}>{loading?i18nText('正在读取链上活动…'):i18nText('刷新活动')}</button></div><p className="fine">{i18nText("以下为八个已部署的测试网测试团，非市场或真实用户；进入活动后确认最新报价。")}</p>
 <div className="catalog-controls"><div className="catalog-filters" aria-label={i18nText("按场景筛选")}>{Object.entries(names).map(([value,label])=><button key={value} type="button" aria-pressed={category===value} onClick={()=>setCategory(value)}>{label}</button>)}</div><label className="catalog-search">{i18nText("查找活动")}<input aria-label={i18nText("查找活动")} placeholder={i18nText("活动名称或编号")} value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 {(catalogError||error)&&<p role="alert" className="error-text">{catalogError||error}{i18nText("。可以刷新重试，也可通过活动链接直接进入。")}</p>}
 <div className="catalog-grid">{shown.map(entry=>{const g=cards[entry.id],stale=g&&now-g.fetchedAt>15000;return <article className={`catalog-card ${entry.featured?'featured':''}`} key={entry.id} data-group-id={entry.id} data-category={entry.category}><div className="catalog-eyebrow"><span>{entry.featured?i18nText('主活动'):names[entry.category]||i18nText('测试活动')} · #{entry.id}</span><span>{g&&!g.error?cardStatus(g):i18nText('正在核对')}</span></div><h3>{g?.title||i18nText("正在读取活动 #{0}", entry.id)}</h3>{!g?<div className="skeleton"/>:g.error?<p role="status">{i18nText("该活动读取失败，未展示假价格。")}<a href={destination(`/g/${entry.id}`,d)}>{i18nText("打开活动重试 →")}</a></p>:<><div className="catalog-finance"><div><span>{g.quote!==null?(g.funded?i18nText('现在加入'):i18nText('预报名款')):i18nText('固定总价')}</span><Amount value={g.quote??g.cost} deployment={d}/></div><div><span>{i18nText("当前／保留名单")}</span><strong>{g.count}<small> / {g.capacity} {i18nText("人")}</small></strong></div></div>{stale&&<p className="error-text">{i18nText("列表快照较旧；进入活动重新核价，不按旧价付款。")}</p>}<a className={entry.featured?'primary':'secondary'} href={destination(`/g/${entry.id}`,d)}>{g.quote!==null?i18nText('查看活动与最新报价'):i18nText('查看状态与公开收据')} →</a></>}</article>})}</div>
 {!shown.length&&!loading&&!catalogError&&<p role="status">{i18nText("没有匹配的活动。清空搜索或选择其他分类。")}</p>}</section>;
}
export function HostGroupList({deployment:d,ids,onManage}:{deployment:Deployment;ids:bigint[];onManage:(id:bigint)=>void}){
 const [limit,setLimit]=useState(8);const selected=useMemo(()=>[...ids].reverse().slice(0,limit).map(String),[ids,limit]);const {cards,loading,error,reload}=useGroupCards(d,selected);
 return <><button className="text-button" onClick={()=>void reload()}>{i18nText("刷新活动摘要")}</button>{error&&<p role="alert">{error}</p>}<div className="host-group-cards">{selected.map(id=>{const g=cards[id];return <article key={id}><div><span className="fine">{i18nText("活动 #")}{id}</span><h3>{g?.title||i18nText('正在读取活动名称')}</h3><p>{g&&!g.error?i18nText("{0} · {1}/{2} 人", cardStatus(g), g.count, g.capacity):g?.error?i18nText('读取失败，点击管理重试'):i18nText('正在读取链上状态')}</p>{g&&!g.error&&<Amount value={g.cost} deployment={d}/>}</div><div className="host-actions"><button className="secondary" onClick={()=>onManage(BigInt(id))}>{i18nText("读取并管理")}</button><a className="text-button" href={destination(`/g/${id}`,d)}>{i18nText("公开活动 ↗")}</a></div></article>})}</div>{ids.length>limit&&<button className="secondary" disabled={loading} onClick={()=>setLimit(n=>n+8)}>{i18nText("再显示 8 个活动")}</button>}</>;
}
